[build]
  publish = "public"
  functions = "netlify/functions"

[dev]
  port = 8888
  functions = "netlify/functions"

[[redirects]]
  from = "/api/proxy"
  to = "/.netlify/functions/proxy"
  status = 200

[[redirects]]
  from = "/api/books"
  to = "/.netlify/functions/books"
  status = 200

[[redirects]]
  from = "/api/movies"
  to = "/.netlify/functions/movies"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
